server: fix lastMulticast map concurrent access
When both IPv4 and IPv6 are used, lastMulticast may be accessed
concurrently because mainloop() spawns receive functions for v4
and v6 from independent goroutines, and both eventually call
handleQuery().

Fixes: https://github.com/celebdor/zeroconf/pull/3

fatal error: concurrent map read and map write

goroutine 10 [running]:
runtime.throw(0x862f66, 0x21)
	/usr/lib/golang/src/runtime/panic.go:1117 +0x72 fp=0xc00003cd18 sp=0xc00003cce8 pc=0x43bdf2
runtime.mapaccess2_fast64(0x7f2620, 0xc000072870, 0x4, 0xc00001000c, 0xc00003cde0)
	/usr/lib/golang/src/runtime/map_fast64.go:61 +0x1ac fp=0xc00003cd40 sp=0xc00003cd18 pc=0x41822c
github.com/celebdor/zeroconf.(*Server).handleQuery(0xc00005a240, 0xc00003ceb0, 0x4, 0x8d4bf8, 0xc0004b0000, 0x0, 0x0)
	/go/src/github.com/openshift/mdns-publisher/vendor/github.com/celebdor/zeroconf/server.go:366 +0x2f3 fp=0xc00003ce78 sp=0xc00003cd40 pc=0x666933
github.com/celebdor/zeroconf.(*Server).parsePacket(0xc00005a240, 0xc000228000, 0x29, 0x10000, 0x4, 0x8d4bf8, 0xc0004b0000, 0xc0004b0000, 0x0)
	/go/src/github.com/openshift/mdns-publisher/vendor/github.com/celebdor/zeroconf/server.go:323 +0xfc fp=0xc00003cf48 sp=0xc00003ce78 pc=0x6665fc
github.com/celebdor/zeroconf.(*Server).recv6(0xc00005a240, 0xc0000645f0)
	/go/src/github.com/openshift/mdns-publisher/vendor/github.com/celebdor/zeroconf/server.go:309 +0x16f fp=0xc00003cfd0 sp=0xc00003cf48 pc=0x66648f
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00003cfd8 sp=0xc00003cfd0 pc=0x471741
created by github.com/celebdor/zeroconf.(*Server).mainloop
	/go/src/github.com/openshift/mdns-publisher/vendor/github.com/celebdor/zeroconf/server.go:211 +0x65

Signed-off-by: Dan Williams <dcbw@redhat.com>